# Generated by Django 5.1.7 on 2025-05-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuoora', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
