# Generated by Django 5.1.7 on 2025-05-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuoora', '0003_question_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
